language: cpp
compiler: gcc
sudo: require
dist: trusty

script:
  - appimage/build-appimage

after_success:
  - cd appimage/build
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./qpdf*.AppImage https://transfer.sh/qpdf-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - sha512sum ./qpdf*.AppImage
